DATASET:
  desc: fashion_mnist or cifar100
  value: mnist
NUM_EPOCHS:
  value: 100
BATCH_SIZE:
  value: 125
USE_ROUTING:
  value: False
LR_INITIAL:
  value: 0.01
MOMENTUM:
  value: 0.9
DROPOUT_RATE:
  value: 0.35
CNN_0:
  value: 20
CNN_1:
  value: 50
